general.import = [
  "~/.config/alacritty/catppuccin.toml"
]

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.85

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
#family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
#family = "CaskaydiaCove Nerd Font"
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
# family = "CaskaydiaCove Nerd Font"
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
style = "Regular"

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]
